on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Download source
        uses: actions/checkout@v4

      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/shards
          key: ${{ runner.os }}-arm64-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-arm64-shards-

      - name: Build binary in ARM container
        run: |
          docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/workspace -w /workspace \
            -v /home/runner/.cache/shards:/root/.cache/shards \
            crystallang/crystal:latest-alpine \
            sh -c "
              git config --global --add safe.directory /workspace && \
              apk add --no-cache ruby && \
              crystal tool format --check && \
              shards check || shards install --without-development && \
              shards build --production --progress --no-debug -Dstrict_multi_assign -Dno_number_autocast --static --link-flags='-s -Wl,-z,relro,-z,now'
            "

      - name: Collect package information
        run: |
          echo "BINARY_NAME=bin/$(cat shard.yml |grep targets -A1|tail -n1 |sed 's#[ :]##g')" >> $GITHUB_ENV
          echo "PKG_ARCH=arm64" >> $GITHUB_ENV
          echo "PLATFORM=unknown-linux-musl.tar.gz" >> $GITHUB_ENV

      - name: Set asset name
        run: |
          echo "ASSET_NAME=${{env.BINARY_NAME}}-${{github.ref_name}}-${{env.PKG_ARCH}}-${{env.PLATFORM}}" >> $GITHUB_ENV

      - name: Package release asset
        id: release
        run: |
          echo "ASSET_NAME=${{env.ASSET_NAME}}" >> $GITHUB_OUTPUT
          tar zcvf ${{env.ASSET_NAME}} ${{env.BINARY_NAME}} LICENSE

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{steps.release.outputs.ASSET_NAME}}
