on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: ~/.cache/shards
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-

      - name: Download source
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Check formatting
        run: crystal tool format --check

      - name: Install shards
        run: shards check || shards install

      - name: Run Ameba
        run: bin/ameba

      - name: Run typer
        run: bin/typer src/procodile.cr
        
      - name: Run tests
        run: scripts/test.sh
        
      - name: Build docs
        run: crystal docs
        
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
